sudo: required
language: generic
services:
- docker
env:
  global:
  - secure: cf1UZFSfaPjz9aQ+M8u+6yfZk81DWZoTzmIT9UxCZmwZH8kkb9zADjnLONaOB6jMk6Meyxau76ZACKL8szNd7BcOsL0M5nBpBoUIVc+Lbe+g02TFsm956yfk5FISbK7AUC/Qblhw9jQeyT7qFyeyh711/f3C+jwXFB9P9uxK2PjsUpz0BeQH6ld/wnappNQla3IDM+vLaHv1CmH2y9sLl3WDhs9jVHPUPhzeklgojibvHXRe2wcdytlII4Vh79+kDKCUUncNkPNFqrcY4ISluRGIchTsjy9AR2/MezbS3T3Ei6w4CqTlIT3hRr6B7mQrdXx4rTCKKucafFB2KcFp9cBcqeWZ++B/u/tXyb49nGcuNxQz2zoY0u3Ba5TLelwbQLH8X55meVeJLrDShOTX+PHiNK070o7luz8LDqE1O6WCD3Ne+GcOv1B2uaPT3TkNUNxt82rSaDHwHQWa9/2foELglo+W/ca6SmZb10McyJSaZn50XIquy0g/oMNhkvqTQVYklY5ztbKMqv4hXtiA+Rq1RMWJxDs9OkgQWafPmrTJOO8djf7rEhexfJuVVaOBOFzQZCjv0F+/DqP+E6YpZp2whvjga+/1mp/Nno7UIutJs8GLNONdA4un/EHky0U2BlD6NTH/DePKZWImwzYQSQdGK2xsnA2XH9QM6ZvMWBk=
  - secure: FEjVU4qL2PBa0LKBGrIRxrWwqplBIf1HbOI+asD6C+woCfdvn2Hv58W339qTGCtHszJYUhLKfPx1Q9c8MriF1PZ4OWFqCI7LHz20IwfDGFXV+nN/WIjRrJWLWLbb2co2gY0mAd22+3ZWKJsqKueum0aKYv3Ba5jwiIfbvEFVG39cLDhVxfxIBmn7AtCEjsdOaDUhbuwde+SBLfC+Zc2IM7PlcAio9ZqGCveKE4Kz1pjcgsWG/kTckNow/zY4o8laOY8OUGFp+wTWQY4EGp9vc6dwQKankrUKhpU3hU261aoyOToZiGvqQCXuNiaAev3SgScLmkIkoSacr03W3xXuQ8ifocHZ8BaZD3fHCYyucORoDPr0s7ak/O8VEqCkasKK8yAD5WH4j9Klidl5dxjL23TCnqtrcHaDKz+5jF81ZONQkoBsFc/Q+4DT9TO01SnJ9uOQYs+FtNNg6GmoskdDFbTAGnC36Q9eb6ofJ+Z37PmfCPqCv36PPOIkaDwpVMdw817bOT/uJs9pgP64Ko8HsdfEHxZp0SZv5qRPUPE/XtoCzIv4cx3Htu1uoxVPDW+YY8gZfQIT8zVR44NqTyJ0DYgx+VZ1DO2bVxMu+2mn8m7aZ/eCHTD8WX7AnbL3GPTVrdvTzGkbAERAIOwFtCq9GPp9Xdc3rtzbg5eN4esWd1w=
  - COMMIT=${TRAVIS_COMMIT::8}
before_install:
- sudo apt-get update
- sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-engine
script:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- export REPO=webide/webjars-builder
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH
  ; fi`
- docker build -f Dockerfile -t $REPO:$COMMIT .
- docker tag $REPO:$COMMIT $REPO:$TAG
- docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
- docker push $REPO
notifications:
  slack:
    on_failure: always
    on_success: change
    rooms:
      secure: Njx9s1blHlbNr8L73/+R5i9aDDCKvDRMfwZ7FrscuGH8OoLeH41VLEw1hmCVb/TxWmC5p8A36vzT7YWpWAStqEvwUSCQH10n8LRJkmaBK1WCXeaMJBf99C2DHbysCwI8OY1k71YYqU7essNnLZLUQiDSAtfdhcHHxgUvHoqVSgD08dZNjKVUeBHxAR0x7AS+/8cpqsMsGYhmGxUDDxuH3SblzSCP/NAvGc8p0+9dsDxyzY6j+l1mfFU31Y1AQulKYba/Na3g9O/s4MW6qqbSbh3qTY2scH0GNexNS+HPM01qUnCM0juZE1kREVNQFakxyHItn6LqWQxedJ4FSn6YARxixIwE1BhFiuok6FQlPz5w+kvMZeO0Oe8ngU6qaNvydW+XVzvJomUZGeRTqbOwXJrSC6mgeRQsaPs5gxak3+2K6uE74HjQn2zz3yYDJ5YB9T4Y7ZYnRNhEIaqvYVI1D+dFjV1OhvL4789uSThhcS+tAS6p8OH4ZZkTnlvvpkVsIo3walOu1w8alum+5wjXKmF9Dry1gy6cX379AjkmJoZXdng7tsHB25OPY0duXD7l+vN1iythWn3LP9GVfs9FswzV2FgVEY/DFgZXr2aMggWLn87ygHW6Uvz+MWcMcnW/nvM3ZvHGPH/PModWagNAOnUsSC0FgvOIPyKJgB7b7V0=
